// <auto-generated />
using FacturasOnline.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace FacturasOnline.Migrations
{
    [DbContext(typeof(FODbContext))]
    [Migration("20171006131027_AddUserAccountantsTable2")]
    partial class AddUserAccountantsTable2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FacturasOnline.Core.Models.InvoiceInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("InvoiceDate");

                    b.Property<string>("InvoiceName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int>("PhotoId");

                    b.HasKey("Id");

                    b.ToTable("InvoiceInfo");
                });

            modelBuilder.Entity("FacturasOnline.Core.Models.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("userName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Photo");
                });

            modelBuilder.Entity("FacturasOnline.Core.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FullName");

                    b.Property<DateTime>("LastLogin");

                    b.Property<string>("userName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FacturasOnline.Core.Models.UsersAccountants", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("UserAccountant")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("UsersAccountants");
                });
#pragma warning restore 612, 618
        }
    }
}
